[2025-02-11 13:19:28,897] 11 root - INFO - Logging started
[2025-02-11 13:19:42,695] 11 root - INFO - Data Ingestion Started
[2025-02-11 13:19:50,200] 53 root - INFO - Data was splitted in to two 
[2025-02-11 13:19:50,201] 54 root - INFO - Exited split_data_as_train-test method of data ingestion class
[2025-02-11 13:19:50,201] 57 root - INFO - Exporting the train and test data
[2025-02-11 13:19:50,299] 60 root - INFO - splitted Data is saved at location 
[2025-02-11 13:19:50,414] 31 root - INFO - NUmber of columns are2
[2025-02-11 13:19:50,415] 32 root - INFO - NUmber of columns areIndex(['having_IP_Address', 'URL_Length', 'Shortining_Service',
       'having_At_Symbol', 'double_slash_redirecting', 'Prefix_Suffix',
       'having_Sub_Domain', 'SSLfinal_State', 'Domain_registeration_length',
       'Favicon', 'port', 'HTTPS_token', 'Request_URL', 'URL_of_Anchor',
       'Links_in_tags', 'SFH', 'Submitting_to_email', 'Abnormal_URL',
       'Redirect', 'on_mouseover', 'RightClick', 'popUpWidnow', 'Iframe',
       'age_of_domain', 'DNSRecord', 'web_traffic', 'Page_Rank',
       'Google_Index', 'Links_pointing_to_page', 'Statistical_report',
       'Result'],
      dtype='object')
[2025-02-11 13:19:50,416] 31 root - INFO - NUmber of columns are2
[2025-02-11 13:19:50,416] 32 root - INFO - NUmber of columns areIndex(['having_IP_Address', 'URL_Length', 'Shortining_Service',
       'having_At_Symbol', 'double_slash_redirecting', 'Prefix_Suffix',
       'having_Sub_Domain', 'SSLfinal_State', 'Domain_registeration_length',
       'Favicon', 'port', 'HTTPS_token', 'Request_URL', 'URL_of_Anchor',
       'Links_in_tags', 'SFH', 'Submitting_to_email', 'Abnormal_URL',
       'Redirect', 'on_mouseover', 'RightClick', 'popUpWidnow', 'Iframe',
       'age_of_domain', 'DNSRecord', 'web_traffic', 'Page_Rank',
       'Google_Index', 'Links_pointing_to_page', 'Statistical_report',
       'Result'],
      dtype='object')
[2025-02-11 13:19:50,448] 22 root - ERROR - Error occured at script name [D:\Mlops\DS2\src\components\data_validation.py] line number [79] error message [Error occured at script name [D:\Mlops\DS2\src\components\data_validation.py] line number [55] error message [cannot access local variable 'is_found' where it is not associated with a value]]
